FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY *.sln .
COPY OperacoesService/*.csproj ./OperacoesService/
RUN dotnet restore OperacoesService/OperacoesService.csproj

COPY . .
WORKDIR /src/OperacoesService
RUN dotnet publish -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "OperacoesService.dll"]
